Use dedicated error function
Signed-off-by: Tyler Nijmeh <tylernij@gmail.com>

diff --git a/charch b/charch
--- a/charch
+++ b/charch
@@ -1,6 +1,11 @@
 #!/bin/bash
 # Written by Draco (tytydraco) @ GitHub
 
+err() {
+	echo -e "\e[91m[!] $@\e[39m"
+	exit 1
+}
+
 # Path containing rootfs tarball and all rootfs instances
 if [[ -d "/home" ]]
 then
@@ -39,11 +44,7 @@ while getopts "d:n:u:C:cfiUh" opt; do
 		n)
 			ROOTFS="$OPTARG"
 
-			if [[ "$ROOTFS" == *[/.]* ]]
-			then
-				echo "[!] Rootfs name contains illegal characters. Exiting."
-				exit 1
-			fi
+			[[ "$ROOTFS" == *[/.]* ]] && err "Rootfs name contains illegal characters. Exiting."
 			;;
 		u)
 			ROOTFS_URL="$OPTARG"
@@ -92,36 +93,20 @@ ENV=(
 # Check for required dependencies
 for dep in chroot curl env find id mkdir mount mountpoint readlink rm sed tar unarch wc
 do
-	if ! command -v "$dep" &> /dev/null
-	then
-		echo "[!] Unable to locate dependency $dep. Exiting."
-		exit 1
-	fi
+	! command -v "$dep" &> /dev/null && err "Unable to locate dependency $dep. Exiting."
 done
 
 # Check for root permissions
-if [[ `id -u` -ne 0 ]]
-then
-	echo "[!] No root permissions. Exiting."
-	exit 1
-fi
+[[ `id -u` -ne 0 ]] && err "No root permissions. Exiting."
 
 fetch_rootfs() {
 	if [[ ! -f "$CHROOT_DIR/rootfs.tar.gz" ]] || [[ "$FORCE_FETCH" -eq 1 ]]
 	then
-		if [[ -z "$ROOTFS_URL" ]]
-		then
-			echo "[!] No rootfs tarball URL specified. Exiting."
-			exit 1
-		fi
+		[[ -z "$ROOTFS_URL" ]] && err "No rootfs tarball URL specified. Exiting."
 
 		curl -# -L -o "$CHROOT_DIR/rootfs.tar.gz" "$ROOTFS_URL"
 
-		if [[ $? -ne 0 ]]
-		then
-			echo "[!] Failed to fetch rootfs tarball. Exiting."
-			exit 1
-		fi
+		[[ $? -ne 0 ]] && err "Failed to fetch rootfs tarball. Exiting."
 	fi
 }
 
@@ -129,11 +114,7 @@ setup_rootfs() {
 	mkdir -p "$ROOTFS_DIR"
 	tar xf "$CHROOT_DIR/rootfs.tar.gz" -C "$ROOTFS_DIR" &> /dev/null
 
-	if [[ $? -ne 0 ]]
-	then
-		echo "[!] Failed to extract rootfs tarball. Exiting."
-		exit 1
-	fi
+	[[ $? -ne 0 ]] && err "Failed to extract rootfs tarball. Exiting."
 
 	# Check for nested rootfs directory
 	local dircount=`ls "$ROOTFS_DIR" | wc -w`
@@ -158,11 +139,7 @@ safe_mount() {
 		mount -t "$type" "$type" "$ROOTFS_DIR/$name"
 
 		# Fail check
-		if [[ $? -ne 0 ]]
-		then
-			echo "[!] Failed to mount $type. Exiting."
-			exit 1
-		fi
+		[[ $? -ne 0 ]] && err "Failed to mount $type. Exiting."
 	fi
 }
 
@@ -178,11 +155,7 @@ safe_bind() {
 		mount --bind "/$name" "$ROOTFS_DIR/$name"
 
 		# Fail check
-		if [[ $? -ne 0 ]]
-		then
-			echo "[!] Failed to mount $name. Exiting."
-			exit 1
-		fi
+		[[ $? -ne 0 ]] && err "Failed to mount $name. Exiting."
 	fi
 }
 
@@ -256,11 +229,7 @@ post_install() {
 # Create a new rootfs instance
 if [[ "$CREATE" -eq 1 ]]
 then
-	if [[ -d "$ROOTFS_DIR" ]]
-	then
-		echo "[!] Rootfs instance already exists at $ROOTFS_DIR. Exiting."
-		exit 1
-	fi
+	[[ -d "$ROOTFS_DIR" ]] && err "Rootfs instance already exists at $ROOTFS_DIR. Exiting."
 
 	# Create initial chroot home
 	[[ ! -d "$CHROOT_DIR" ]] && mkdir -p "$CHROOT_DIR"
@@ -277,11 +246,7 @@ then
 	# Fix common chroot issues and do post-install config
 	post_install &> /dev/null
 else
-	if [[ ! -d "$ROOTFS_DIR" ]]
-	then
-		echo "[!] No rootfs instance at $ROOTFS_DIR. Exiting."
-		exit 1
-	fi
+	[[ ! -d "$ROOTFS_DIR" ]] && err "No rootfs instance at $ROOTFS_DIR. Exiting."
 
 	# Mount host binds
 	setup_mounts
diff --git a/cparch b/cparch
--- a/cparch
+++ b/cparch
@@ -1,6 +1,11 @@
 #!/bin/bash
 # Written by Draco (tytydraco) @ GitHub
 
+err() {
+	echo -e "\e[91m[!] $@\e[39m"
+	exit 1
+}
+
 # Path containing rootfs tarball and all rootfs instances
 if [[ -d "/home" ]]
 then
@@ -35,11 +40,7 @@ while getopts "d:h" opt; do
 done
 shift $((OPTIND-1))
 
-if [[ "$1 $2" == *[/.]* ]]
-then
-	echo "[!] Rootfs name contains illegal characters. Exiting."
-	exit 1
-fi
+[[ "$1 $2" == *[/.]* ]] && err "Rootfs name contains illegal characters. Exiting."
 
 # Add busybox components from Magisk
 [[ -d "/sbin/.magisk/busybox" ]] && [[ "$PATH" != *"/sbin/.magisk/busybox"* ]] &&
@@ -48,19 +49,11 @@ fi
 # Check for required dependencies
 for dep in cp id unarch
 do
-	if ! command -v "$dep" &> /dev/null
-	then
-		echo "[!] Unable to locate dependency $dep. Exiting."
-		exit 1
-	fi
+	! command -v "$dep" &> /dev/null && err "Unable to locate dependency $dep. Exiting."
 done
 
 # Check for root permissions
-if [[ `id -u` -ne 0 ]]
-then
-	echo "[!] No root permissions. Exiting."
-	exit 1
-fi
+[[ `id -u` -ne 0 ]] && err "No root permissions. Exiting."
 
 # Usage check
 if [[ "$#" -ne 2 ]]
@@ -70,18 +63,10 @@ then
 fi
 
 # Check if chroot container exists
-if [[ ! -d "$CHROOT_DIR" ]]
-then
-	echo "[!] No container at $CHROOT_DIR. Exiting."
-	exit 1
-fi
+[[ ! -d "$CHROOT_DIR" ]] && err "No container at $CHROOT_DIR. Exiting."
 
 # Check for existing destination rootfs
-if [[ -d "$CHROOT_DIR/$2" ]]
-then
-	echo "[!] Rootfs instance with name $2 already exists. Exiting."
-	exit 1
-fi
+[[ -d "$CHROOT_DIR/$2" ]] && err "Rootfs instance with name $2 already exists. Exiting."
 
 # Unmount and exit on fail
 unarch -d "$CHROOT_DIR" -n "$1"
diff --git a/lsarch b/lsarch
--- a/lsarch
+++ b/lsarch
@@ -1,6 +1,11 @@
 #!/bin/bash
 # Written by Draco (tytydraco) @ GitHub
 
+err() {
+	echo -e "\e[91m[!] $@\e[39m"
+	exit 1
+}
+
 # Path containing rootfs tarball and all rootfs instances
 if [[ -d "/home" ]]
 then
@@ -46,26 +51,14 @@ shift $((OPTIND-1))
 # Check for required dependencies
 for dep in find id
 do
-	if ! command -v "$dep" &> /dev/null
-	then
-		echo "[!] Unable to locate dependency $dep. Exiting."
-		exit 1
-	fi
+	! command -v "$dep" &> /dev/null && err "Unable to locate dependency $dep. Exiting."
 done
 
 # Check for root permissions
-if [[ `id -u` -ne 0 ]]
-then
-	echo "[!] No root permissions. Exiting."
-	exit 1
-fi
+[[ `id -u` -ne 0 ]] && err "No root permissions. Exiting."
 
 # Check if chroot container exists
-if [ ! -d "$CHROOT_DIR" ]
-then
-	echo "[!] No container at $CHROOT_DIR. Exiting."
-	exit 1
-fi
+[[ ! -d "$CHROOT_DIR" ]] && err "No container at $CHROOT_DIR. Exiting."
 
 # Display paths to available rootfs instances
 if [[ "$LIST_TARBALLS" -eq 1 ]]
diff --git a/rmarch b/rmarch
--- a/rmarch
+++ b/rmarch
@@ -1,6 +1,11 @@
 #!/bin/bash
 # Written by Draco (tytydraco) @ GitHub
 
+err() {
+	echo -e "\e[91m[!] $@\e[39m"
+	exit 1
+}
+
 # Path containing rootfs tarball and all rootfs instances
 if [[ -d "/home" ]]
 then
@@ -32,11 +37,7 @@ while getopts "d:n:tah" opt; do
 		n)
 			ROOTFS="$OPTARG"
 
-			if [[ "$ROOTFS" == *[/.]* ]]
-			then
-				echo "[!] Rootfs name contains illegal characters. Exiting."
-				exit 1
-			fi
+			[[ "$ROOTFS" == *[/.]* ]] && err "Rootfs name contains illegal characters. Exiting."
 			;;
 		t)
 			RM_TARBALL=1
@@ -66,26 +67,14 @@ ROOTFS_DIR="$CHROOT_DIR/$ROOTFS"
 # Check for required dependencies
 for dep in id readlink rm unarch
 do
-	if ! command -v "$dep" &> /dev/null
-	then
-		echo "[!] Unable to locate dependency $dep. Exiting."
-		exit 1
-	fi
+	! command -v "$dep" &> /dev/null && err "Unable to locate dependency $dep. Exiting."
 done
 
 # Check for root permissions
-if [[ `id -u` -ne 0 ]]
-then
-	echo "[!] No root permissions. Exiting."
-	exit 1
-fi
+[[ `id -u` -ne 0 ]] && err "No root permissions. Exiting."
 
 # Check if chroot container exists
-if [[ ! -d "$CHROOT_DIR" ]]
-then
-	echo "[!] No container at $CHROOT_DIR. Exiting."
-	exit 1
-fi
+[[ ! -d "$CHROOT_DIR" ]] && err "No container at $CHROOT_DIR. Exiting."
 
 # Handle tarball removal
 if [[ "$RM_TARBALL" -eq 1 ]] && [[ -f "$CHROOT_DIR/rootfs.tar.gz" ]]
@@ -106,11 +95,7 @@ then
 fi
 
 # Check if rootfs exists
-if [[ ! -d "$ROOTFS_DIR" ]]
-then
-	echo "[!] No rootfs instance at $ROOTFS_DIR. Exiting."
-	exit 1
-fi
+[[ ! -d "$ROOTFS_DIR" ]] && err "No rootfs instance at $ROOTFS_DIR. Exiting."
 
 # Try to unmount rootfs mounts
 unarch -d "$CHROOT_DIR" -n "$ROOTFS"
diff --git a/unarch b/unarch
--- a/unarch
+++ b/unarch
@@ -1,6 +1,11 @@
 #!/bin/bash
 # Written by Draco (tytydraco) @ GitHub
 
+err() {
+	echo -e "\e[91m[!] $@\e[39m"
+	exit 1
+}
+
 # Path containing rootfs tarball and rootfs instances
 if [[ -d "/home" ]]
 then
@@ -34,11 +39,7 @@ while getopts "d:n:ah" opt; do
 		n)
 			ROOTFS="$OPTARG"
 
-			if [[ "$ROOTFS" == *[/.]* ]]
-			then
-				echo "[!] Rootfs name contains illegal characters. Exiting."
-				exit 1
-			fi
+			[[ "$ROOTFS" == *[/.]* ]] && err "Rootfs name contains illegal characters. Exiting."
 			;;
 		a)
 			UNMOUNT_ALL=1
@@ -65,26 +66,14 @@ ROOTFS_DIR="$CHROOT_DIR/$ROOTFS"
 # Check for required dependencies
 for dep in awk grep id lsarch mount readlink seq umount
 do
-	if ! command -v "$dep" &> /dev/null
-	then
-		echo "[!] Unable to locate dependency $dep. Exiting."
-		exit 1
-	fi
+	! command -v "$dep" &> /dev/null && err "Unable to locate dependency $dep. Exiting."
 done
 
 # Check for root permissions
-if [[ `id -u` -ne 0 ]]
-then
-	echo "[!] No root permissions. Exiting."
-	exit 1
-fi
+[[ `id -u` -ne 0 ]] && err "No root permissions. Exiting."
 
 # Check if chroot container exists
-if [ ! -d "$CHROOT_DIR" ]
-then
-	echo "[!] No container at $CHROOT_DIR. Exiting."
-	exit 1
-fi
+[[ ! -d "$CHROOT_DIR" ]] && err "No container at $CHROOT_DIR. Exiting."
 
 unmount_rootfs() {
 	for i in `seq $RETRY_CNT`
@@ -114,8 +103,7 @@ unmount_rootfs() {
 	done
 
 	# If we made it this far, we failed one or more unmounts
-	echo "[!] Failed to unmount $fullpath. Exiting."
-	exit 1
+	err "Failed to unmount $fullpath. Exiting."
 }
 
 # Unmount the rootfs filesystems
@@ -127,11 +115,7 @@ then
 	done
 else
 	# Check if rootfs exists
-	if [[ ! -d "$ROOTFS_DIR" ]]
-	then
-		echo "[!] No rootfs instance at $ROOTFS_DIR. Exiting."
-		exit 1
-	fi
+	[[ ! -d "$ROOTFS_DIR" ]] && err "No rootfs instance at $ROOTFS_DIR. Exiting."
 
 	unmount_rootfs "$ROOTFS_DIR"
 fi
